version: "3.9"
services:
  robo3t:
    image: njordr/robo3t:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
